### ISSUE TITLE
Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by mdshah930** [DylanSnyder31/AlphaZero-Chess#3]
Can you help me solve this error
 raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by tamirha2530** [comment]
Hi! I solved this problem. you need to change the line of code:
"self.Neural_Network_Architecture = Neural_Network_Architecture().cuda()" to: "self.Neural_Network_Architecture = Neural_Network_Architecture().cpu()"

**Comment by Laur1sXd** [comment]
Where to change that?
